# Generated by Django 2.2.6 on 2019-11-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0004_auto_20191123_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='inn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='third_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
