# Generated by Django 2.2.6 on 2019-11-23 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
