# Generated by Django 2.2.6 on 2019-11-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uber', '0005_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscribers',
            new_name='Subscriber',
        ),
        migrations.AddField(
            model_name='mentor',
            name='login',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='login',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
